project_id = "deal-blast-pro"

[auth]
site_url = "https://deal-blast-pro.vercel.app"
additional_redirect_urls = [
  "https://deal-blast-pro.vercel.app/auth/callback",
  "https://deal-blast-pro.vercel.app/auth/callback?type=email_change",
  "https://deal-blast-os7xzf8hh-housebuyerinv.vercel.app/auth/callback",
  "https://deal-blast-os7xzf8hh-housebuyerinv.vercel.app/auth/callback?type=email_change",
  "https://deal-blast-9xx91z9ps-housebuyerinv.vercel.app/auth/callback",
  "https://deal-blast-9xx91z9ps-housebuyerinv.vercel.app/auth/callback?type=email_change",
  "https://deal-blast-5hf2jhe04-housebuyerinv.vercel.app/auth/callback",
  "https://deal-blast-5hf2jhe04-housebuyerinv.vercel.app/auth/callback?type=email_change",
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
