import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabaseClient'

async function adminRequest(action: string, init: RequestInit = {}) {
  const { data } = await supabase.auth.getSession()
  const response = await fetch(`/api/property-intelligence/${action}`, { ...init, headers: { Authorization: `Bearer ${data.session?.access_token || ''}`, ...(init.body ? { 'Content-Type': 'application/json' } : {}), ...(init.headers || {}) } })
  const payload = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(payload?.error || 'Owner Admin data could not be loaded.')
  return payload
}

export default function AdminCustomerLifecycle() {
  const [data, setData] = useState<any>({ kpis: {}, customers: [] })
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [subject, setSubject] = useState('Try Deal Blast Pro Free for 14 Days + 20% Off'); const [message, setMessage] = useState('Deal Blast Pro now includes a 14-day Pro trial. Explore advanced buyer matching, Deal Blast Builder, follow-up tools, calculators, Hot Zones, and more. Use LAUNCH20 for 20% off your first paid month.'); const [audience, setAudience] = useState('all'); const [campaign, setCampaign] = useState<any>(null); const [recipientCount, setRecipientCount] = useState(0); const [campaignBusy, setCampaignBusy] = useState(false)
  useEffect(() => { void (async()=>{setLoading(true);try{setData(await adminRequest('admin-customer-lifecycle'));const preview=await adminRequest('admin-announcement-campaign?audience=all');setRecipientCount(preview.previewRecipientCount||0)}catch(e:any){setError(e.message)}finally{setLoading(false)}})() }, [])
  useEffect(() => { void adminRequest(`admin-announcement-campaign?audience=${encodeURIComponent(audience)}`).then(p => setRecipientCount(p.previewRecipientCount || 0)).catch(() => {}) }, [audience])
  const customers = useMemo(() => (data.customers || []).filter((c:any) => { const text=`${c.name} ${c.email} ${c.workspace} ${c.currentPlan} ${c.billingStatus}`.toLowerCase(); if(query&&!text.includes(query.toLowerCase()))return false;if(filter==='trial')return c.billingStatus==='Trial Active';if(filter==='paid')return c.billingStatus==='Paid Active';if(filter==='past_due')return c.billingStatus==='Past Due';return true }), [data.customers,query,filter])
  const campaignOp = async (operation:string) => { setCampaignBusy(true); setError(''); try { const body:any={operation,subject,message,audience:{kind:audience}}; if(campaign?.id)body.campaignId=campaign.id;if(operation==='queue')body.confirmed=true;const result=await adminRequest('admin-announcement-campaign',{method:'POST',body:JSON.stringify(body)});if(result.campaign)setCampaign(result.campaign);if(operation==='test')alert('Test message queued to the verified Owner Admin address.');if(operation==='queue')alert(`${result.queued} campaign messages queued.`) } catch(e:any){setError(e.message)} finally{setCampaignBusy(false)} }
  const kpiEntries=[['Total Signups',data.kpis.totalSignups],['Free',data.kpis.free],['Starter Paid',data.kpis.starterPaid],['Pro Trials',data.kpis.proTrials],['Pro Paid',data.kpis.proPaid],['Agency',data.kpis.agency],['Trials Ending Soon',data.kpis.trialsEndingSoon],['Trial → Paid',data.kpis.trialConversions],['Past Due',data.kpis.pastDue],['Canceled',data.kpis.cancelled]]
  return <section className="space-y-4" aria-labelledby="customer-lifecycle-title">
    <div className="card border border-sky-500/25 p-4"><div className="text-xs uppercase tracking-[2px] text-[#8B92A3]">Owner Admin Only</div><h2 id="customer-lifecycle-title" className="text-lg font-semibold">Customer & Subscriber Lifecycle</h2>{error&&<div className="mt-3 text-sm text-red-300">{error}</div>}<div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-5">{kpiEntries.map(([label,value])=><div className="panel p-3" key={label}><div className="text-xs text-[#8B92A3]">{label}</div><div className="text-xl font-semibold">{loading?'—':value||0}</div></div>)}</div>
    <div className="mt-4 flex gap-2"><input className="input flex-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, workspace, plan…"/><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="trial">Pro Trials</option><option value="paid">Paid</option><option value="past_due">Past Due</option></select></div>
    <div className="mt-3 max-h-[420px] overflow-auto"><table className="w-full text-xs"><thead><tr className="text-left text-[#8B92A3]"><th className="p-2">Customer</th><th className="p-2">Plan / billing</th><th className="p-2">Trial</th><th className="p-2">PI entitlement</th><th className="p-2">Usage</th></tr></thead><tbody>{customers.map((c:any)=><tr key={c.workspaceId} className="border-t border-[#252A38]"><td className="p-2"><div>{c.name||c.workspace}</div><div className="text-[#8B92A3]">{c.email}</div></td><td className="p-2">{c.currentPlan}<div className="text-[#8B92A3]">{c.billingStatus} · {c.subscriptionStatus||'—'}</div></td><td className="p-2">{c.trialEnd?`${c.daysRemaining} days · ${new Date(c.trialEnd).toLocaleDateString()}`:'—'}</td><td className="p-2">{c.paidPiEntitlement?'Paid allowance eligible':'No paid allowance'}<div className="text-[#8B92A3]">Limit {c.includedPiLimit}</div></td><td className="p-2">{c.buyerCount} buyers · {c.dealCount} deals</td></tr>)}</tbody></table></div></div>
    <div className="card border border-violet-500/25 p-4"><div className="text-xs uppercase tracking-[2px] text-[#8B92A3]">Intentional delivery only</div><h2 className="text-lg font-semibold">Product Announcement Campaign</h2><div className="mt-4 grid gap-3"><input className="input" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><textarea className="input min-h-28" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Message"/><select className="select" value={audience} onChange={e=>setAudience(e.target.value)}><option value="all">All eligible users</option><option value="free">Free</option><option value="starter">Starter</option><option value="pro_trial">Pro Trial</option><option value="pro_paid">Pro Paid</option><option value="agency">Agency</option><option value="non_paying">Non-paying users</option><option value="trials_ending_soon">Trials ending soon</option><option value="recent_signups">Recent signups (30 days)</option></select><div className="text-sm text-[#C5CAD6]">Preview: {recipientCount} opted-in recipients. Suppressions are enforced again by the existing outbox worker.</div><div className="flex flex-wrap gap-2"><button className="btn btn-primary" disabled={campaignBusy} onClick={()=>void campaignOp('draft')}>Save Draft</button><button className="btn btn-ghost" disabled={!campaign?.id||campaignBusy} onClick={()=>void campaignOp('test')}>Send Owner Test</button><button className="btn btn-green" disabled={!campaign?.id||campaignBusy} onClick={()=>{if(confirm(`Queue this campaign for ${recipientCount} recipients?`))void campaignOp('queue')}}>Confirm & Queue</button></div></div></div>
  </section>
}
